# Generated by Django 5.2 on 2025-05-12 20:26

import course.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.URLValidator(),
                    course.validators.validate_youtube_url,
                ],
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
