# Generated by Django 5.2 on 2025-05-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_lesson_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                default="https://www.youtube.com/watch?v=default",
                help_text="Добавьте ссылку на видео",
                verbose_name="Ссылка на видео",
            ),
            preserve_default=False,
        ),
    ]
